version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: aprovame
      RABBITMQ_DEFAULT_PASS: aprovame
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - ./dist:/app/dist
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
